# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "file", source: "provision", destination: "/tmp/provision"
  config.vm.provision "shell", path: "./provision/install.sh"
end
