# -*- mode: ruby -*-
# vi: set ft=ruby :

$build_number = ENV['BUILD_NUMBER'] || "0"

Vagrant.configure("2") do |config|
    (1..2).each do |i|
        config.vm.define "k8s#{i}#{$build_id_name}" do |server|
            server.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", "2048"]
                vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
            end
            server.vm.box = "wholebits/ubuntu17.04-64"
            server.vm.hostname = "k8s#{i}"
            server.vm.provision "file", source: "provision", destination: "/tmp/provision"
            server.vm.provision "shell", path: "./provision/k8s_install.sh"
            server.vm.network "private_network",
                ip: "192.168.36.1#{i}",
                virtualbox__intnet: "cilium-k8s#{$build_id_name}"
        end
    end
end
