# -*- mode: ruby -*-
# vi: set ft=ruby :

$build_number = ENV['BUILD_NUMBER'] || "0"

Vagrant.configure("2") do |config|
    (1..2).each do |i|
        config.vm.define "k8s#{i}#{$build_id_name}" do |server|
            server.vm.provider "virtualbox" do |vb|
                # vb.customize ["modifyvm", :id, "--memory", "2048"]
                vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
                vb.cpus = 2
                vb.memory=2048
            end

            server.vm.box = "wholebits/ubuntu17.04-64"
            server.vm.hostname = "k8s#{i}"
            server.vm.network "private_network",
                ip: "192.168.36.1#{i}",
                virtualbox__intnet: "cilium-k8s#{$build_id_name}"

            # Provision section
            server.vm.provision "file", source: "provision", destination: "/tmp/provision"
            server.vm.provision "shell" do |sh|
				sh.path = "./provision/k8s_install.sh"
				sh.args = ["k8s#{i}", "192.168.36.1#{i}"]
			end
        end
    end
end
